name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Debug environment
        run: |
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Package.json exists: $(test -f package.json && echo 'yes' || echo 'no')"
          echo "Package-lock.json exists: $(test -f package-lock.json && echo 'yes' || echo 'no')"
          echo "Lockfile version: $(head -5 package-lock.json | grep lockfileVersion || echo 'not found')"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
